name: silentsos_mobile_application
description: >
  SilentSOS+ is a dual-mode emergency alert app for both public/medical and covert personal threats,
  with Firebase backend and React.js admin panel.

publish_to: 'none' # This app won't be published to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter




  # ğŸŒˆ UI & Material
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  path_provider: ^2.1.3

  # ğŸ”¥ Firebase Core & Services
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.9
  firebase_database: ^11.3.5
  firebase_messaging: ^15.2.7
  firebase_storage: ^12.0.0
  intl: ^0.18.1
  timeago: ^3.3.0
  flutter_animate: ^4.3.0
  url_launcher: ^6.2.6  # or the latest version
  app_settings: ^5.1.1
  android_intent_plus: ^4.0.1

  # ğŸŒ Location & Sensors
  geolocator: ^14.0.1
  battery_plus: ^5.0.1
  permission_handler: ^11.0.1

  # ğŸ—ºï¸ Google Maps
  google_maps_flutter: ^2.5.0

  # ğŸ› ï¸ Utilities
  http: ^1.4.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
